export const checkMailConstants = {
    //Check Mail
    CHECKMAIL_REQUEST: "CHECKMAIL_REQUEST",
    CHECKMAIL_FAILURE: "CHECKMAIL_FAILURE",
    CHECKMAIL_SUCCESS: "CHECKMAIL_SUCCESS",
}

export const authConstants = {
    //LOGIN
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",

    //LOGOUT
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    //SIGNUP
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
}